### ISSUE TITLE
hardcoded base language

### ISSUE THREAD

**Issue by nandod** [mlocati/betterpoeditor#12]
In frmMain.cs, at line 1153, there's a hard-coded "en" base language for Bing translations:

```
string translated = Utils.BingTranslator.Translate("en", this.CurrentPO.Language.TwoLetterISOLanguageName, from.Text);
```

Since it is possible to use gettext with a base language other than english, it would be useful to have a way to specify it, either as a config option, a selection in the form, or other means.

**Comment by mlocati** [comment]
Thanks @nandod

> Since it is possible to use gettext with a base language other than english

Why do you say his? As far as I know, the original language of gettext should always be English (see [here](https://www.gnu.org/software/gettext/manual/html_node/Preparing-Strings.html#Preparing-Strings))...

For instance, it's impossible to have Russian as a source language.
That's because Russian has more that 2 plural forms, and gettext only allows two plural forms for the source language (namely `msgid` and `msgid_plural`).

**Comment by nandod** [comment]
Almost any western european language will do. I am successfully using gettext with a mixture of english and italian as base languages. But nevermind, I have found a workaround.
Thanks
